Add custom retry logic for cloud run
pulumi/pulumi-google-native pull request #411
Opened 2022-03-24 22:51 UTC by viveklak

Fixes #399.

Adds a heuristic to determine output-ty status fields from types used as inputs and outputs where these were previously being construed as required inputs.

Also adds some machinery to override the metadata for some resources to make one-of fixes easier.

2022-03-25 20:02 UTC, viveklak commented
> ### Does the PR have any schema changes?
> Resource "google-native:dns/v2:ManagedZone" missing input "id"
> Resource "google-native:dns/v2:ManagedZone" missing input "nameServers"
> Resource "google-native:dns/v1beta2:Change" missing input "startTime"
> Resource "google-native:dns/v1beta2:Change" missing input "id"
> Resource "google-native:dns/v1beta2:Change" missing input "status"
> Resource "google-native:sqladmin/v1:BackupRun" missing input "status"
> Resource "google-native:run/v1:Service" missing input "status"
> Resource "google-native:run/v1:DomainMapping" missing input "status"
> Resource "google-native:accesscontextmanager/v1beta:ServicePerimeter" missing input "status"
> Resource "google-native:dns/v1beta2:ResponsePolicy" missing input "id"
> Resource "google-native:deploymentmanager/alpha:CompositeType" missing input "status"
> Resource "google-native:compute/v1:NodeGroup" missing input "status"
> Resource "google-native:dns/v1beta2:ManagedZone" missing input "id"
> Resource "google-native:dns/v1beta2:ManagedZone" missing input "nameServers"
> Resource "google-native:compute/alpha:NodeGroup" missing input "status"
> Resource "google-native:dns/v2:Policy" missing input "id"
> Resource "google-native:dns/v1:Policy" missing input "id"
> Resource "google-native:run/v1alpha1:Job" missing input "status"
> Resource "google-native:accesscontextmanager/v1:ServicePerimeter" missing input "status"
> Resource "google-native:dns/v1beta2:Policy" missing input "id"
> Resource "google-native:deploymentmanager/v2beta:CompositeType" missing input "status"
> Resource "google-native:servicemanagement/v1:Rollout" missing input "status"
> Resource "google-native:sqladmin/v1beta4:BackupRun" missing input "status"
> Resource "google-native:dns/v1:Change" missing input "status"
> Resource "google-native:dns/v1:Change" missing input "id"
> Resource "google-native:dns/v1:Change" missing input "startTime"
> Resource "google-native:compute/beta:NodeGroup" missing input "status"
> Resource "google-native:dns/v1:ManagedZone" missing input "id"
> Resource "google-native:dns/v1:ManagedZone" missing input "nameServers"

These are output-only fields that should not have been modeled as inputs.

> Type "google-native:dns/v2:ChangeStatus" missing
> Type "google-native:dns/v1:ChangeStatus" missing
> Type "google-native:dns/v1beta2:ChangeStatus" missing

These are affected by https://github.com/pulumi/pulumi-google-native/issues/413. I will open a separate PR to introduce these types back (along with other enums which are currently excluded).

2022-03-25 20:04 UTC, viveklak commented on provider/pkg/resources/resources.go
> +	KNativeStatusPoll = PollingStrategy("KNativeStatusPoll")
We will likely have to support additional custom polling mechanisms here. See https://github.com/GoogleCloudPlatform/declarative-resource-client-library/tree/main/dcl/operations

2022-03-25 20:41 UTC, viveklak commented
Reviewer note:
The primary change is in https://github.com/pulumi/pulumi-google-native/pull/411/files#diff-04c663ce0ec07699115794969a983af85f7def6794d0a9170e1c1645c6bf2568 (`poll.go`) where a new custom polling function for knative (cloud run) resources is added. Changes in [`overrides.go`](https://github.com/pulumi/pulumi-google-native/pull/411/files#diff-85d5fad1cb24cc2a4df0556778701885ceb8de1c07b5ea233659933f2d4d8381) and [`schema.go`](https://github.com/pulumi/pulumi-google-native/pull/411/files#diff-4b4c0cf25563429565383180f98332b1dd806ba3fc7b7cd8473ba51435199667) are to add a marker in the metadata for relevant resources for using the custom polling mechanism. I also fixed a couple of issues where output-ty fields (e.g. status) were being marked as input types in the schema causing await issues. This is probably the hackiest part of the PR. This is also the reason why you see schema/sdk changes in this PR.

2022-03-25 20:47 UTC, jkodroff approved these changes
Approved with optional suggestions.

2022-03-25 20:47 UTC, jkodroff commented on provider/pkg/provider/poll.go
> +	// 1. Get generation from metadata
Would like a godoc comment on the func, and this comment removed.

2022-03-25 20:47 UTC, jkodroff commented on provider/pkg/resources/resources.go
> +	DefaultPoll       = PollingStrategy("")
`None`, maybe?

2022-04-05 16:08 UTC, lblackstone requested changes

2022-04-05 20:40 UTC, viveklak commented on provider/pkg/gen/schema.go
> +		}
Not sure. I think i tried to roll this into `isReadOnly` and it was a bit too broad? Lets keep it's usage a bit constrained for now.

2022-04-05 20:42 UTC, viveklak commented on provider/pkg/googleclient/http.go
> -	logging.V(9).Infof(responseFormat, res.Request.Method, res.Request.URL, prettyPrintJSONLines(debugResp))
I believe this has been backported to 1.17 as well: https://github.com/golang/go/issues/49559

2022-04-05 20:54 UTC, viveklak commented on examples/cloudrun-ts/step1/index.ts
> +    location: 'us-east4',
Removed, thanks for the catch.

2022-04-05 20:55 UTC, viveklak commented on provider/pkg/provider/poll.go
> +			log.Printf("[DEBUG] checking KnativeStatus Ready condition %s: %s", condition.Status, condition.Message)
Yup - fixed!

2022-04-05 21:24 UTC, lblackstone approved these changes

2022-04-05 21:24 UTC, merged